---
- name: Pull Docker Images and Run Docker Compose
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
    docker_compose_file: /home/{{ ansible_user }}/docker-compose.yml
  tasks:
    - name: Pull backend image
      docker_image:
        name: yuktax/backend:latest
        source: pull

    - name: Pull frontend image
      docker_image:
        name: yuktax/frontend:latest
        source: pull

    - name: Copy docker-compose file to remote
      copy:
        src: ../docker-compose.yml
        dest: "{{ docker_compose_file }}"
      when: inventory_hostname != 'localhost'

    - name: Run Docker Compose on localhost
      command: docker-compose -f ../docker-compose.yml up -d
      when: inventory_hostname == 'localhost'

    # - name: Run Docker Compose on remote
    #   command: docker-compose -f "{{ docker_compose_file }}" up -d
    #   when: inventory_hostname != 'localhost'
